### ISSUE TITLE
No need to saved an un-modified file in the local history-view

### ISSUE THREAD

**Issue by lmcbout** [vince-fugnitto/local-history-ext#162] opened 2020-06-16 19:53 UTC
**Bug Description**
No need to create a file in local-history when closing an unmodified file. When a user open a file and close it, why do we need to create an unmodified file  in the local-history?

**Steps to Reproduce**
- Open the Output/Local-history view
- Open a file
- Close the file
--> In the output/local history view, an entry is being log and if you re-open the same file, you will see there was a file being saved.
[Info - 03:44:21:4421]: A new revision rebuild_20200616154421_416_m.ts for rebuild.ts has been created at 2020-06-16 15:44:21.416

**Comment by vince-fugnitto** [comment] 2020-06-16 20:07
@lmcbout it is not a bug it is a design decision, we need to make sure that the latest changes of a file are saved (revision) when the editor is closed (either overriding the last save or creating a new one). For example think of the case of if auto-save is off. For simplicity, the extension will create a save.

**Comment by lmcbout** [comment] 2020-06-17 12:44
I think this is not OK. Just opening + closing a file generates a saved in the local-history !. A user can just open + close all files and he will get a duplicate of his whole workspace, but did not modify any files at all !
If the file is dirty, then OK to save the file in local-history,

**Comment by vince-fugnitto** [comment] 2020-06-17 13:05
> I think this is not OK.

@lmcbout for simplicity the extension was designed this way, to create revisions when the editor is closed as to pick up any recent or dirty changes. There is no appropriate API to determine if a file is dirty when it is closed so what exactly do you propose? Do you propose completely removing the creation of revisions when an editor is closed (which has a tradeoff of reduce functionality).

**Closed** 2020-06-17 13:42 UTC
Labels: bug
