### ISSUE TITLE
Version 0.0.2 Save Delay is not respected to create a new file

### ISSUE THREAD

**Issue by lmcbout** [vince-fugnitto/local-history-ext#158] opened 2020-06-16 13:37 UTC
**Description**
With version 0.0.2, the time delay to create a new file is broken. My preference is set to 300000 millisec ( 5 mins) and it creates a new file every few seconds, not every 5 mins

**Checklist**

**Additional Information**

**Comment by vince-fugnitto** [comment] 2020-06-16 13:43
@lmcbout I can not reproduce the issue, the saving takes the `delay` into account correctly.
If the delay is small, multiple revisions will be created while the default will override the last revision.

If you can reproduce, please provide reproduction steps.

**Comment by vince-fugnitto** [comment] 2020-06-16 13:46
I'll do a completely fresh build to verify.

**Comment by vince-fugnitto** [comment] 2020-06-16 13:49
@lmcbout I could not reproduce the issue.

**Comment by lmcbout** [comment] 2020-06-16 13:54
Here a video of the reproduction 

![ShortDelay](https://user-images.githubusercontent.com/419051/84783390-3289f780-afb7-11ea-831a-44c6f37da79c.gif)

**Comment by vince-fugnitto** [comment] 2020-06-16 14:03
@lmcbout I still could not reproduce, did you happen to set the preference at the `workspace` level?

**Comment by lmcbout** [comment] 2020-06-16 14:37
@vince-fugnitto yopu are right, yesterday,  I set the value at the workspace level, it was set to 3 sec for testing purposes. So this morning I was using the user level, so I did not see the other setting.

Question: is there a way we could see when a preference is being set to anything than the default value  at the user, workspace or folder level, so this stupid mistake does not occur again ? We should not have to open and check on each tab to see if the preference value is set or not. Also, in the preference view, when switching from user to workspace, the list of preference rewturn to the top of the list, it does not maintain his position in the tree.

Question 2: I also noticed on the console a lot of errors happening when modifying a lione in a file:
- root ERROR Child node 'file-change-tree-root' does not belong
- root ERROR [hosted-plugin: 24929] TextEditor is disposed!
- root ERROR [hosted-plugin: 24929] Error processing request. Cannot read property 'enable' of undefined
- root ERROR [hosted-plugin: 24929] With stack trace: Error: <semantic> TypeScript Server Error (3.8.3)

**Comment by vince-fugnitto** [comment] 2020-06-16 14:41
> @vince-fugnitto you are right, yesterday

Thank you for confirming, I will close the issue.

> Question: is there a way we could see when a preference is being set to anything than the default value at the user, workspace or folder level, so this stupid mistake does not occur again ?

It used to be the case that the `preferences-ui` showed that the file has been modified at a more specific scope, perhaps it is a regression.

> Question 2: I also noticed on the console a lot of errors happening when modifying a lione in a file:

The logs look unrelated to the extension, I believe it happens with the `scm` view on `master`.

**Closed by vince-fugnitto** 2020-06-16 14:41 UTC
